<a href="https://colab.research.google.com/github/kleeresearch/TextAnalysis/blob/master/Course/Day3/12_doc_vectorization_example1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer # frequency based DTM
from sklearn.feature_extraction.text import TfidfVectorizer # tf-idf based DTM

In [2]:
TEXT = ['banana apple apple eggplant',
        'orange carrot banana eggplant',
        'apple carrot banana banana',
        'orange banana grape'
]

# CountVectorizer 이용하기

In [3]:
tf_vectorizer = CountVectorizer(min_df=1, max_df=0.8, ngram_range=(1,1))
tf_features = tf_vectorizer.fit_transform(TEXT)

In [4]:
print(tf_features)

  (0, 0)	2
  (0, 2)	1
  (1, 2)	1
  (1, 4)	1
  (1, 1)	1
  (2, 0)	1
  (2, 1)	1
  (3, 4)	1
  (3, 3)	1


In [5]:
features = np.array(tf_features.todense())
features

array([[2, 0, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1]])

In [6]:
features.shape

(4, 5)

In [7]:
features[0]

array([2, 0, 1, 0, 0])

In [8]:
features[1]

array([0, 1, 1, 0, 1])

In [9]:
np.linalg.norm(features[1]-features[0])

2.449489742783178

In [10]:
np.linalg.norm(features[1]-features[2])

1.7320508075688772

In [11]:
feature_names = tf_vectorizer.get_feature_names_out()
feature_names

array(['apple', 'carrot', 'eggplant', 'grape', 'orange'], dtype=object)

In [12]:
import pandas as pd
df = pd.DataFrame(data=features, columns=feature_names)
print(df)

   apple  carrot  eggplant  grape  orange
0      2       0         1      0       0
1      0       1         1      0       1
2      1       1         0      0       0
3      0       0         0      1       1


# TfidfVectorizer 이용하기

In [13]:
tfidf_vectorizer = TfidfVectorizer(min_df=1, ngram_range=(1,1))
tfidf_features = tfidf_vectorizer.fit_transform(TEXT)

In [14]:
tfidf_features = np.array(tfidf_features.todense())
tfidf_features

array([[0.85764287, 0.28383251, 0.        , 0.42882143, 0.        ,
        0.        ],
       [0.        , 0.35696573, 0.53931298, 0.53931298, 0.        ,
        0.53931298],
       [0.51623315, 0.68337886, 0.51623315, 0.        , 0.        ,
        0.        ],
       [0.        , 0.37919167, 0.        , 0.        , 0.72664149,
        0.5728925 ]])

In [15]:
tfidf_features[0]

array([0.85764287, 0.28383251, 0.        , 0.42882143, 0.        ,
       0.        ])