<a href="https://colab.research.google.com/github/kleeresearch/TextAnalysis/blob/master/Course/Day5/18_LR_iris_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
iris = pd.read_csv('/content/drive/MyDrive/KOSSDA_텍스트마이닝_강의자료/강의자료/Day4/python_code/iris_data.csv')

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           7.0          3.2           4.7          1.4        0
1           6.4          3.2           4.5          1.5        0
2           6.9          3.1           4.9          1.5        0
3           5.5          2.3           4.0          1.3        0
4           6.5          2.8           4.6          1.5        0

In [4]:
iris_np = iris.values

In [5]:
iris_np

array([[7. , 3.2, 4.7, 1.4, 0. ],
       [6.4, 3.2, 4.5, 1.5, 0. ],
       [6.9, 3.1, 4.9, 1.5, 0. ],
       [5.5, 2.3, 4. , 1.3, 0. ],
       [6.5, 2.8, 4.6, 1.5, 0. ],
       [5.7, 2.8, 4.5, 1.3, 0. ],
       [6.3, 3.3, 4.7, 1.6, 0. ],
       [4.9, 2.4, 3.3, 1. , 0. ],
       [6.6, 2.9, 4.6, 1.3, 0. ],
       [5.2, 2.7, 3.9, 1.4, 0. ],
       [5. , 2. , 3.5, 1. , 0. ],
       [5.9, 3. , 4.2, 1.5, 0. ],
       [6. , 2.2, 4. , 1. , 0. ],
       [6.1, 2.9, 4.7, 1.4, 0. ],
       [5.6, 2.9, 3.6, 1.3, 0. ],
       [6.7, 3.1, 4.4, 1.4, 0. ],
       [5.6, 3. , 4.5, 1.5, 0. ],
       [5.8, 2.7, 4.1, 1. , 0. ],
       [6.2, 2.2, 4.5, 1.5, 0. ],
       [5.6, 2.5, 3.9, 1.1, 0. ],
       [5.9, 3.2, 4.8, 1.8, 0. ],
       [6.1, 2.8, 4. , 1.3, 0. ],
       [6.3, 2.5, 4.9, 1.5, 0. ],
       [6.1, 2.8, 4.7, 1.2, 0. ],
       [6.4, 2.9, 4.3, 1.3, 0. ],
       [6.6, 3. , 4.4, 1.4, 0. ],
       [6.8, 2.8, 4.8, 1.4, 0. ],
       [6.7, 3. , 5. , 1.7, 0. ],
       [6. , 2.9, 4.5, 1.5, 0. ],
       [5.7, 2

In [6]:
iris_features = iris_np[:,:-1]
iris_labels = iris_np[:,-1]

In [7]:
iris_features.shape

(100, 4)

In [8]:
iris_labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_features, iris_labels, test_size = 0.3, random_state=0)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
lr_base = LogisticRegression(penalty='none')

In [12]:
lr_base.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


LogisticRegression(penalty='none')

In [13]:
lr_base.coef_

array([[-150.04874422, -156.78486711,  238.18962206,  177.4973587 ]])

In [14]:
lr_base.intercept_

array([-83.73727923])

In [15]:
len(y_test)

30

In [16]:
lr_base.score(X_test, y_test)

0.9333333333333333

In [17]:
y_predictions = lr_base.predict(X_test)

In [18]:
y_predictions

array([0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.])

In [19]:
y_test

array([0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.])

In [20]:
from sklearn.metrics import accuracy_score
y_predictions = lr_base.predict(X_test)
accuracy_score(y_test, y_predictions)

0.9333333333333333

예측을 통해서 가지는 종속변수의 값이 된다. 값이 동일한 것을 알 수 있다.

## Regularization (규제화) 적용하기

In [21]:
lr_p1 = LogisticRegression(C=0.1, penalty='l1', solver = 'saga', max_iter=1000)

람다와 C의 값은 반비례

saga 는 경사하강법과 비슷한데 약간 심화한 것.

C의 값을 0.1로 줄이면 람다 값이 10이 됨. -> 파라미터값 coef가 0 이 되는 것들이 생김. penalty=L1  방법을 써서 그럼. 해당 독립변수 feature가 제거가 된다. 모형이 단순화되는 효과가 있다. 너무 단순화되면 다른 문제가 발생한다. under fitting problem 학습 데이터가 설명 못하는 문제가 생긴다. 적당한 수준으로 복잡하게 해야 한다.


L2 방법을 썼을 때는 0까지 줄어드는 애들은 없음. L1 과 다르게 0까지 줄어들지 않는다. L1에 비해서 계산 속도가 더 빠르다. 모형의 성능을 평가하기 위해서 정밀도를 사용하면 된다. 추가적으로 이론을 말하면 됨.


로지스틱 회귀 모형의 경우에는 여러가지 방법들을 쓴 다음에 최선의 방법을 선택하는 것. 검증 데이터라고 하는 것을 쪼개서 학습의 과정에서 비용한수의 과정을 파악해서 학습데이터에 대한 비용함수를 설며한다. 학습에 사용디지 않은 검증데이터가 설명력이 약해지면 과적합이 발생한다. 규제화를 써보고 과적합 문제 판단.


학습데이터에 설명하지 못하는 것




C = Inverse of regularization strength, 즉 C 값이 작을수록 penalty를 많이 준다는 것입니다.<br>
solver => 어떠한 방법을 사용해서 optimal한 parameter의 방법을 찾는지에 대한것

In [22]:
lr_p1.fit(X_train, y_train)

LogisticRegression(C=0.1, max_iter=1000, penalty='l1', solver='saga')

In [23]:
lr_p1.coef_

array([[0.       , 0.       , 1.3491413, 0.       ]])

In [24]:
lr_p1.coef_

array([[0.       , 0.       , 1.3491413, 0.       ]])

In [25]:
lr_p1.score(X_test, y_test)

0.8666666666666667

In [26]:
lr_p2 = LogisticRegression(C=1, penalty='l2', solver='saga', max_iter=1000)

In [27]:
lr_p2.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(C=1, max_iter=1000, solver='saga')

In [28]:
lr_p2.score(X_test, y_test)

0.9333333333333333

In [29]:
lr_p2.coef_

array([[-0.61727636, -0.79587889,  2.52696958,  1.9004148 ]])

## Check model performance

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predictions)

array([[13,  2],
       [ 0, 15]])

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predictions))

              precision    recall  f1-score   support

         0.0       1.00      0.87      0.93        15
         1.0       0.88      1.00      0.94        15

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

